---
- hosts: "{{ host }}"
  gather_facts: False
  become: yes
  become_method: enable
  become_user: root

  tasks:
    - name: Joining the cluster
      command: sudo riak-admin cluster join riak@"{{ primary_host }}"
      register: join
      tags: join

    - debug:
        var: join
   
    - name: Get Riak Admin Cluster Plan
      command: sudo riak-admin cluster plan
      register: plan
      tags: plan

    - debug:
        var: plan

    - name: Get Riak Admin Cluster status
      command: sudo riak-admin cluster status
      register: status
      tags: status

    - debug:
        var: status
